# coding: utf-8
from django.conf.urls import patterns, url
from viajes.views import CartaPorteView

urlpatterns = patterns('viajes.views',    
    (r'^add/$', 'agregar'),    
    (r'^edit/(?P<viaje_id>\d+)/$', 'editar'),
    (r'^carga/$', 'carga'),
    (r'^cargaedit/(?P<viaje_id>\d+)/$', 'cargaedit'),    
    (r'^historial/(?P<viaje_id>\d+)/$', 'historial'),   
    (r'^actualizar/(?P<viaje_id>\d+)/$', 'actualizar'),
    (r'^solicitado/(?P<viaje_id>\d+)/$', 'solicitado'),  
    (r'^salida/(?P<viaje_id>\d+)/$', 'salida'),
    (r'^llegada/(?P<viaje_id>\d+)/$', 'llegada'),  
    (r'^entrega/(?P<viaje_id>\d+)/$', 'entrega'),
    (r'^facturado/(?P<viaje_id>\d+)/$', 'facturado'),
    (r'^comprobantes/(?P<viaje_id>\d+)/$', 'comprobante'), 
    (r'^gasto/(?P<gasto_id>\d+)/$', 'comprobantegasto'),
    (r'^comprobante/upload/(?P<gasto_id>\d+)/$', 'comprobante_upload'),
    (r'^comprobante/delete/(?P<comprobante_id>\d+)/$', 'comprobante_delete'),   
    (r'^cambio/(?P<viaje_id>\d+)/$', 'cambio'),   
    (r'^rutas/$', 'rutas'), 
    (r'^rutas/add/$', 'rutasadd'),
    (r'^rutas/modal/$', 'rutasmodal'),
    (r'^rutas/add/(?P<ruta_id>\d+)$', 'rutasadd'),    
    (r'^rutas/edit/(?P<ruta_id>\d+)/$', 'rutasedit'),
    (r'^reportes/$', 'reportes'),
    (r'^subirExcel/$', 'subirExcel'),
    (r'^reportes/results/$', 'reportesresults'),
    (r'^reportes/reportsexcel/$', 'reportsexcel'),
    url(r"^carta_porte/(?P<pk>\d+)/$", CartaPorteView.as_view(), name='carta_porte'),
    (r'^$', 'index'),
    (r'^fact/$','index_fact'),
)
